In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(X_train,y_train),(X_test,y_test) = mnist.load_data()

X_train,X_test = X_train/255.0, X_test/255.0

11493376/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential(

        [tf.keras.layers.Flatten(input_shape=(28,28)),
        tf.keras.layers.Dense(128,activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)]
)

In [6]:
model(X_train[:1]).numpy()

array([[ 0.6083105 ,  0.88609695,  0.73975974,  0.50383687,  0.9937723 ,
         0.66603816,  0.06530958,  0.02825314, -0.5851827 ,  0.23873052]],
      dtype=float32)

In [7]:
tf.nn.softmax(model(X_train[:1]).numpy()).numpy()

array([[0.11078791, 0.14626268, 0.1263514 , 0.0997976 , 0.16289072,
        0.11737164, 0.06436801, 0.06202642, 0.03358651, 0.07655716]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], model(X_train[:1]).numpy()).numpy()

2.14241

In [11]:
model.compile(optimizer='adam',loss=loss_fn,metrics=["accuracy"])

In [12]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4790 - accuracy: 0.8598
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1532 - accuracy: 0.9558
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1099 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0872 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0719 - accuracy: 0.9772


In [14]:
model.evaluate(X_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0730 - accuracy: 0.9775


[0.07304053008556366, 0.9775000214576721]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(X_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.57393026e-07, 5.46193357e-09, 2.43757700e-06, 2.80268170e-04,
        3.86511526e-12, 3.39733219e-07, 7.08047512e-14, 9.99710262e-01,
        1.62195704e-07, 6.20652145e-06],
       [3.34790617e-09, 4.28048588e-05, 9.99950409e-01, 2.57848740e-07,
        3.46287556e-16, 7.50981144e-08, 6.26613961e-09, 5.12640094e-14,
        6.43144494e-06, 5.23181388e-16],
       [2.05804653e-08, 9.99764979e-01, 1.21946978e-04, 3.40456472e-06,
        1.12769876e-05, 6.80948324e-06, 5.28516296e-07, 5.85358612e-05,
        3.24191897e-05, 9.98747538e-08],
       [9.99902725e-01, 9.57376667e-09, 6.93732800e-05, 1.13314016e-07,
        3.74545664e-07, 8.82042059e-06, 5.33622961e-06, 3.74190972e-06,
        4.25309679e-07, 9.11699317e-06],
       [4.92582421e-06, 1.41943027e-10, 2.08393667e-05, 1.90136671e-08,
        9.98074293e-01, 2.77817293e-07, 3.64988091e-06, 8.68377465e-05,
        2.28036765e-06, 1.80697301e-03]], dtype=float32)>